import { Product, Supplier, StockMovement, Purchase } from '@/types/inventory';

// Initial sample data
export const initialProducts: Product[] = [
  {
    id: '1',
    code: 'MAT001',
    name: 'Papel A4',
    description: 'Papel sulfite A4 75g/m²',
    unit: 'Resma',
    category: 'Papelaria',
    minStock: 50,
    currentStock: 45,
    location: 'A1-P01',
    lastUpdated: new Date(),
  },
  {
    id: '2',
    code: 'MAT002',
    name: 'Caneta Esferográfica Azul',
    description: 'Caneta esferográfica azul 1.0mm',
    unit: 'Caixa',
    category: 'Papelaria',
    minStock: 20,
    currentStock: 8,
    location: 'A1-P02',
    lastUpdated: new Date(),
  },
  {
    id: '3',
    code: 'MAT003',
    name: 'Toner HP 85A',
    description: 'Cartucho de toner HP CE285A',
    unit: 'Unidade',
    category: 'Informática',
    minStock: 10,
    currentStock: 15,
    location: 'B2-I01',
    lastUpdated: new Date(),
  },
  {
    id: '4',
    code: 'MAT004',
    name: 'Mouse USB',
    description: 'Mouse óptico USB com fio',
    unit: 'Unidade',
    category: 'Informática',
    minStock: 15,
    currentStock: 25,
    location: 'B2-I02',
    lastUpdated: new Date(),
  },
  {
    id: '5',
    code: 'MAT005',
    name: 'Álcool 70%',
    description: 'Álcool etílico 70% 1L',
    unit: 'Litro',
    category: 'Limpeza',
    minStock: 30,
    currentStock: 12,
    location: 'C1-L01',
    lastUpdated: new Date(),
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: '1',
    code: 'FORN001',
    name: 'Papelaria Central LTDA',
    cnpj: '12.345.678/0001-90',
    contact: 'João Silva',
    email: 'contato@papelariacentral.com.br',
    phone: '(11) 3456-7890',
    address: 'Rua das Flores, 123',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01234-567',
    active: true,
  },
  {
    id: '2',
    code: 'FORN002',
    name: 'Tech Suprimentos ME',
    cnpj: '98.765.432/0001-10',
    contact: 'Maria Santos',
    email: 'vendas@techsuprimentos.com.br',
    phone: '(11) 9876-5432',
    address: 'Av. Tecnologia, 456',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '02345-678',
    active: true,
  },
  {
    id: '3',
    code: 'FORN003',
    name: 'Limpeza Total EIRELI',
    cnpj: '45.678.901/0001-23',
    contact: 'Pedro Oliveira',
    email: 'comercial@limpezatotal.com.br',
    phone: '(11) 2345-6789',
    address: 'Rua da Limpeza, 789',
    city: 'Guarulhos',
    state: 'SP',
    zipCode: '03456-789',
    active: true,
  },
];

export const initialMovements: StockMovement[] = [
  {
    id: '1',
    date: new Date(Date.now() - 86400000 * 5),
    type: 'entry',
    productId: '1',
    productName: 'Papel A4',
    quantity: 100,
    unitPrice: 25.00,
    totalValue: 2500.00,
    supplierId: '1',
    supplierName: 'Papelaria Central LTDA',
    documentNumber: 'NF-001234',
    notes: 'Reposição mensal',
  },
  {
    id: '2',
    date: new Date(Date.now() - 86400000 * 3),
    type: 'exit',
    productId: '1',
    productName: 'Papel A4',
    quantity: 55,
    requestedBy: 'Carlos Mendes',
    department: 'Administrativo',
    reason: 'Uso diário',
  },
  {
    id: '3',
    date: new Date(Date.now() - 86400000 * 2),
    type: 'entry',
    productId: '3',
    productName: 'Toner HP 85A',
    quantity: 20,
    unitPrice: 85.00,
    totalValue: 1700.00,
    supplierId: '2',
    supplierName: 'Tech Suprimentos ME',
    documentNumber: 'NF-005678',
  },
  {
    id: '4',
    date: new Date(Date.now() - 86400000),
    type: 'exit',
    productId: '3',
    productName: 'Toner HP 85A',
    quantity: 5,
    requestedBy: 'Ana Paula',
    department: 'TI',
    reason: 'Manutenção impressoras',
  },
];

export const initialPurchases: Purchase[] = [
  {
    id: '1',
    date: new Date(),
    supplierId: '1',
    supplierName: 'Papelaria Central LTDA',
    items: [
      {
        productId: '1',
        productName: 'Papel A4',
        quantity: 50,
        unitPrice: 25.00,
        totalPrice: 1250.00,
      },
      {
        productId: '2',
        productName: 'Caneta Esferográfica Azul',
        quantity: 30,
        unitPrice: 35.00,
        totalPrice: 1050.00,
      },
    ],
    totalValue: 2300.00,
    status: 'pending',
    documentNumber: 'PED-2024001',
    notes: 'Reposição urgente de material de escritório',
  },
];

export function getStockStatus(current: number, min: number): 'critical' | 'warning' | 'normal' {
  const percentage = (current / min) * 100;
  if (percentage <= 50) return 'critical';
  if (percentage <= 80) return 'warning';
  return 'normal';
}