// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-inventory.ts
import { createClient } from "npm:@supabase/supabase-js@^2.57.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_inventory_default = defineTool({
  name: "list_inventory",
  title: "Listar estoque",
  description: "Lista produtos do estoque com nome, categoria, quantidade atual e m\xEDnimo. Suporta filtro por texto e limite.",
  inputSchema: {
    search: z.string().trim().optional().describe("Filtro por nome ou categoria."),
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de itens (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("products").select("id,name,category,quantity,minimum_stock,unit,average_cost").order("name").limit(limit ?? 50);
    if (search) q = q.or(`name.ilike.%${search}%,category.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/low-stock.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.57.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var low_stock_default = defineTool2({
  name: "low_stock_products",
  title: "Produtos com estoque baixo",
  description: "Retorna produtos cuja quantidade em estoque est\xE1 abaixo ou pr\xF3xima do m\xEDnimo (cr\xEDtico/aten\xE7\xE3o).",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("products").select("id,name,category,quantity,minimum_stock,unit").order("quantity").limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const low = (data ?? []).filter(
      (p) => Number(p.quantity ?? 0) <= Number(p.minimum_stock ?? 0) * 1.5
    );
    return {
      content: [{ type: "text", text: JSON.stringify(low) }],
      structuredContent: { products: low }
    };
  }
});

// src/lib/mcp/tools/list-suppliers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.57.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_suppliers_default = defineTool3({
  name: "list_suppliers",
  title: "Listar fornecedores",
  description: "Lista fornecedores cadastrados (nome, CNPJ e contato).",
  inputSchema: {
    search: z3.string().trim().optional(),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("suppliers").select("id,name,cnpj,email,phone,city,state").order("name").limit(limit ?? 50);
    if (search) q = q.or(`name.ilike.%${search}%,cnpj.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { suppliers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-purchases.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.57.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_purchases_default = defineTool4({
  name: "list_purchases",
  title: "Listar compras",
  description: "Lista pedidos de compra recentes, opcionalmente filtrados por status.",
  inputSchema: {
    status: z4.string().trim().optional().describe("Ex: pendente, recebido."),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("purchases").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { purchases: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-requests.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.57.4";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_requests_default = defineTool5({
  name: "list_material_requests",
  title: "Listar requisi\xE7\xF5es de material",
  description: "Lista requisi\xE7\xF5es recebidas (form_responses), com status pendente / realizado / entregue.",
  inputSchema: {
    bucket: z5.enum(["pending", "ordered", "completed", "all"]).optional(),
    limit: z5.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bucket, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser5(ctx).from("form_responses").select("*").order("submitted_at", { ascending: false }).limit(limit ?? 50);
    if (bucket === "completed") q = q.eq("completed", true);
    else if (bucket === "ordered") q = q.eq("ordered", true).eq("completed", false);
    else if (bucket === "pending") q = q.eq("ordered", false).eq("completed", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { requests: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xmaeixjvbpgwkhipaxys";
var mcp_default = defineMcp({
  name: "colormidia-mcp",
  title: "ColorM\xEDdia - Controle de Estoque",
  version: "0.1.0",
  instructions: "Ferramentas para consultar o sistema de Controle de Estoque / Compras da ColorM\xEDdia: estoque, produtos com estoque baixo, fornecedores, compras e requisi\xE7\xF5es de material. Todas as chamadas respeitam as permiss\xF5es (RLS) do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_inventory_default, low_stock_default, list_suppliers_default, list_purchases_default, list_requests_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
