// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmaeixjvbpgwkhipaxys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtYWVpeGp2YnBnd2toaXBheHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MjY1OTksImV4cCI6MjA3NDIwMjU5OX0.1nWBr31FZ666jnxARpMHRK0veWPwjt1hU5n6KxwACdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});